### ISSUE TITLE
Why isn't my site title on my post pages?

### ISSUE THREAD

**Issue by david-bakin** [monkeyWzr/hugo-theme-cactus#111]
I have a fairly vanilla hugo-theme-cactus setup for my blog.  But with this setup, though the main site page (index) has both the site title and site logo, none of the post pages do: they only have the post title (they do have the collapsed menu off to the right).

I'm not really sure what to look at to fix this.

Goal: each post page shows the site title + logo + maybe the description above the post title.

**Comment by LandonFerg** [comment]
The header is defined as a hugo partial template already, so to include the header in your post pages, simply edit the 
`layouts > posts > single.html` file to include the line `{{ partial "header.html" . }}` somewhere after the main content div.

**Comment by david-bakin** [comment]
That was it.  Thanks!
