### ISSUE TITLE
Move from Stylus to SCSS

### ISSUE THREAD

**Issue by Nizzlay** [monkeyWzr/hugo-theme-cactus#15]
Hugo has native support for SCSS. It would be a better fit for the project. It can result in not having to include the pre-rendered CSS files in the source. Can use Hugo to minify the resulting CSS, and provide sourcemaps.

**Comment by Nizzlay** [comment]
Sadly, I'm not good with (S)CSS. I asked some guy on Fiverr to make it work. He delivered me this: [assets.zip](https://github.com/monkeyWzr/hugo-theme-cactus/files/5824613/assets.zip)

It works for the dark theme.

in `head.html` I have this code:

```
{{- $options := (dict "targetPath" "main.css" "outputStyle" "compressed" "enableSourceMap" "true") -}}
{{- $styles := resources.Get "/main.scss" | resources.ToCSS $options }}
<link rel = 'stylesheet' href = '{{ $styles.RelPermalink }}' integrity = '{{ $styles.Data.Integrity }}'>
```

**Comment by monkeyWzr** [comment]
@Nizzlay 
Thank you so much for helping(this one and others)!
And sorry for the delay and lack of response :bow:

**Comment by monkeyWzr** [comment]
@Nizzlay @onweru 
Hi there!
The changes are now merged into the main branch. You can check it out though [gh-pages](https://www.takuzen.me/hugo-theme-cactus/).

And as explained in #64, I changed Sass syntax to SCSS syntax for easier development in the future.

Thanks again and best regards!

**Comment by onweru** [comment]
@monkeyWzr, thank you.

**Comment by Nizzlay** [comment]
@monkeyWzr Thank you :)
