### ISSUE TITLE
Minimum version bumped to 0.55?

### ISSUE THREAD

**Issue by magnific0** [monkeyWzr/hugo-theme-cactus#23]
I'm getting the following error

    ERROR 2020/11/03 15:47:45 render of "home" failed: "/home/xxxx/sites/quickstart/themes/cactus/layouts/index.html:47:118": execute of template failed: template: index.html:47:118: executing "main" at <$elem.Page.Permalink>: can't evaluate field Page in type hugolib.OrderedTaxonomyEntry

when using tags. [Reading online](https://budidev.com/2020/04/getting-errors-order-taxonomies-when-deploy-hugo-site-to-netlify/), this seems to occur if the version is below 0.55. Currently it is 0.48. 

https://github.com/monkeyWzr/hugo-theme-cactus/blob/master/theme.toml#L8

**Comment by monkeyWzr** [comment]
@magnific0 sorry for the delay and really appreciate for pointing that out!
Totally my bad! But I wonder if that is ok for you to upgrade your hugo version to 0.55+? I'm afraid I used a lot of things incompatible with version below 0.55.
Sorry again!

**Comment by magnific0** [comment]
No apologies needed. Just figured I'd report this. Thanks for updating the min version. I switched to testing branch in Debian and now it works great.
