### ISSUE TITLE
How to prevent content/about/index.md from showing as a post?

### ISSUE THREAD

**Issue by netstx** [monkeyWzr/hugo-theme-cactus#3]
My index.md file inside content/about/ shows as a post in the website's home page. Is it possible to prevent this from happening?

Thanks!

**Comment by monkeyWzr** [comment]
My apology for the delay. I'll take a look tonight.

**Comment by netstx** [comment]
> 
> 
> @netstx @Januadrym My apology for the delay. I'll take a look tonight.

No worries, thanks!

**Comment by netstx** [comment]
@monkeyWzr want me to test the commit?

**Comment by monkeyWzr** [comment]
@netstx Would be a great help! Thank you!
