### ISSUE TITLE
Add Reading Time to each post

### ISSUE THREAD

**Issue by amdjml** [monkeyWzr/hugo-theme-cactus#41]
How can I add "Reading Time" to each posts?

**Comment by ungeschneuer** [comment]
This area is not really a support desk but I just saw the question browsing by. Reading time is not implemented in this theme but not that hard to add. You would basically count the words of an entry and divide it by the words per minute a person normally reads. The right template for that would be in cactus/layouts/posts/single.html. Here is a instruction for the code, you would need to add it yourself at the right place. https://kodify.net/hugo/strings/reading-time-text/

**Comment by switchswap** [comment]
I was actually looking to add the same thing and I used @ungeschneuer's link to implement this.

Here's a screenshot on the dark theme (though I made it work for all themes):
![firefox_2021-04-04_05-06-12](https://user-images.githubusercontent.com/26174827/113508275-f2731180-9503-11eb-840c-bae6467d120a.png)

If it looks appropriate, I'd be happy to submit a PR :)

**Comment by ungeschneuer** [comment]
Sounds interesting. Would be probably best to make it optional via variable in the config file.

**Comment by switchswap** [comment]
Ah, I actually did that too via a `showReadTime` boolean.

**Comment by monkeyWzr** [comment]
Thank you all! Merged #42
