### ISSUE TITLE
Images are duplicated in post

### ISSUE THREAD

**Issue by lokamigauti** [monkeyWzr/hugo-theme-cactus#44]
Calling images in a markdown, or Rmarkdown post causes them to appears in the beginning of the post (just link a header/featured image) and in the position where they were called. Follows an example in Hugo 0.81.0:

```
---
title: bug
author: Kamigauti
date: '2021-04-05'
slug: []
categories:
  - programming
tags:
  - R
  - R Blogdown
draft: no
---

# Here comes a image
image:
![](images/ROD_D_03_PM10_ARM_Unmix.png)

# Here comes another image
another one:
![](images/50049767_1006060356246518_5288004544639235541_n.jpg)
```

![image](https://user-images.githubusercontent.com/45218947/113624494-1cc4ec00-9636-11eb-8c96-398406d6c9d1.png)

I do not know if it is indeed a bug or my lack of knowledge about the theme. Thanks for the attention!

**Comment by lokamigauti** [comment]
The same in a fresh install:
![image](https://user-images.githubusercontent.com/45218947/113700330-1756b880-96ad-11eb-9830-1393520df477.png)

**Comment by vdovhanych** [comment]
try using ## and ### for the H1 and H2 insted of just one #. Not seeing this issue.

**Comment by lokamigauti** [comment]
> 
> 
> try using ## and ### for the H1 and H2 insted of just one #. Not seeing this issue.

Same issue usinmg both.

**Comment by natehn** [comment]
I have no problems using [Hugo's figure shortcode](https://gohugo.io/content-management/shortcodes/#figure)

**Comment by lokamigauti** [comment]
I had the same problem. But, I managed to correct it:

I noted that the figures displayed in the top of the post were not necessarily summoned in the .Rmd (or .md), but just in the child directories (in relation of the file directory, I did not tested more than one level down). Somehow hugo scanned the images of all sub directories, regardless of its name, and rendered the images in the post. Another observation is that the images have links to its original image.
So, I created a resources directory above the file dir, and called the image as @natehn suggested (Thank you!):

```
---
title: bug
author: Kamigauti
date: '2021-04-05'
slug: []
categories:
  - programming
tags:
  - R
  - R Blogdown
draft: no
---

# Here comes a image
image:
{{< figure src="../resources/ROD_D_03_PM10_ARM_Unmix.png" >}}

# Here comes another image
another one:
```

And it worked. Not as clean as I would like, but it works perfectly. Thanks for the attention.
