### ISSUE TITLE
Custom fonts and .styl variables

### ISSUE THREAD

**Issue by alamine53** [monkeyWzr/hugo-theme-cactus#45]
Really appreciate your work! 

i'd like to set new Font variables $font-family-body and $font-size. What's the best way to do this?

**Comment by monkeyWzr** [comment]
@alamine53 
Hi there! Sorry for the delay!
This theme now uses Hugo's built-in SCSS pipe (see #67).
you can change `assets/scss/_variables.scss` in the theme folder and then rebuild the blog and It will work.
