### ISSUE TITLE
How are the links that show up in "share post" chosen?

### ISSUE THREAD

**Issue by david-bakin** [monkeyWzr/hugo-theme-cactus#52]
Only two that show up for me are email and ycombinator, but I see in `share.html` there's also code for facebook, linked in, etc.  

What determines which links show up?  Is it related to what you have defined in `[params.social]` in `config.toml`?  I have only gitlab and email defined there, not ycombinator....

**Comment by monkeyWzr** [comment]
@david-bakin Hi there!

There is nothing that can control the share icons numbers, as far as I remembered correctly... I'm sorry but can you provide a capture or something?

`[params.social]` in `config.toml` is used for setting your social link displayed on the homepage and has nothing to do with share icons.

**Comment by terrehbyte** [comment]
@david-bakin Do you have an adblocker installed that potentially blocks elements that link to social media?

I can reproduce the same issue when I turn uBlock Origin OFF and ON:

![image](https://user-images.githubusercontent.com/4968773/117754954-35de3100-b1d0-11eb-9550-0abb52e2a593.png)

**Comment by david-bakin** [comment]
> @david-bakin Do you have an adblocker installed that potentially blocks elements that link to social media?

Yes, that was it, thank you!
