### ISSUE TITLE
[Enhancement] Possibility to set custom logo and ico file

### ISSUE THREAD

**Issue by danieltomasz** [monkeyWzr/hugo-theme-cactus#59]
Would be nice to be able to point to custom logo and ico files in a easy for an user way.

**Comment by daroga0002** [comment]
You can set custom logo.

Here is code responsible for it:
https://github.com/monkeyWzr/hugo-theme-cactus/blob/e735159c5e11fab2d48ed355443b3f7d055ccb8b/layouts/partials/header.html#L2-L8

so to set a cusotm logo set parameter `.Site.Params.logo` or place file in `images.logo.png` then it will be used automaticlly.

Regarding favicon just put it in `images/favicon.ico`


as there is code which will use it:
https://github.com/monkeyWzr/hugo-theme-cactus/blob/e735159c5e11fab2d48ed355443b3f7d055ccb8b/layouts/partials/favicon.html#L2

**Comment by danieltomasz** [comment]
Thanks! I will try to do that creating a files in my main folder that will overide the theme setting!

**Comment by bfeif** [comment]
I'm not able to figure this out ! @daroga0002 or @danieltomasz, can you please explain a little bit more granularly? Precisely where do the new `logo.png` and `favicon.ico` need to go?

**Comment by danieltomasz** [comment]
Hi @bfeif! I dont remeber, but try to substitute files in `static/images`

**Comment by bfeif** [comment]
@danieltomasz It worked! Thanks for helping out a data scientist (and wanna-be developer) 😄
