### ISSUE TITLE
[Feature Request] Copy code button on code blocks

### ISSUE THREAD

**Issue by dhananjaylatkar** [monkeyWzr/hugo-theme-cactus#66]
I think copy code button on code blocks would be a nice addition to this already a great theme.

**Comment by danieltomasz** [comment]
+ 1 for this idea, adding this might involve js https://aaronluna.dev/blog/add-copy-button-to-code-blocks-hugo-chroma/

**Comment by monkeyWzr** [comment]
@dhananjaylatkar @danieltomasz 
Hi there! It is merged from #76. Try it out :D and I would appreciate any ideas!

Thanks and best regards!

**Comment by dhananjaylatkar** [comment]
@monkeyWzr Thanks for quick implementation!!!

Side note -
It looks kind of out of place for now. You can fix colors when you get time or I'll give it a go if you don't mind. :)
