### ISSUE TITLE
enhancement: Support for custom icon

### ISSUE THREAD

**Issue by goakshit** [monkeyWzr/hugo-theme-cactus#96]
#### Overview
Currently, there is no support for the custom icon in the header. Can we add support for that?
Thanks

**Comment by goakshit** [comment]
My bad. It's there but not documented.

**Comment by dalexanderio** [comment]
Do you remember what you did to change it? Sorry to necro.

**Comment by goakshit** [comment]
@dalexanderio The key name `logo`.
```toml

[params]
    logo = "<IMAGE_URL>"
```
I believe it should work as shown above.
