### ISSUE TITLE
Font change

### ISSUE THREAD

**Issue by dhananjaylatkar** [monkeyWzr/hugo-theme-cactus#99]
Is there a way to change font from toml file?

**Comment by slashformotion** [comment]
not unfortunately

**Comment by RobbiNespu** [comment]
@dhananjaylatkar go to themes\cactus\assets\scss\_variables.scss and change it from there

**Comment by burfbari** [comment]
> 

@RobbiNespu can you please elaborate?

**Comment by burfbari** [comment]
thank you... was able to figure out...
